### ISSUE TITLE
Duplicate entries in Programs and Features

### ISSUE THREAD

**Issue by George480** [cryptomator/cryptomator-win#20]
I installed version `1.4.13` on 12th August. A week later, I installed version `1.4.15` but the old version remained (and still is) in `Programs and Features`. 

![Untitled](https://user-images.githubusercontent.com/5148529/64174767-a0b76080-ce62-11e9-984f-f7aa24123066.png)

If I try to uninstall older version it says `Are you sure you want to completely remove Cryptomator and all of its components?` Is it guaranteed that it will not mess up with the files and the latest installed version?

**Comment by overheadhunter** [comment]
This is due to a change we had to do in the installer. This will not change again in the future.

> Is it guaranteed that it will not mess up with the files and the latest installed version?

If you uninstall the old version, it will delete files also needed by Cryptomator 1.4.15, including Cryptomator's settings and saved passwords (see also issue #19).

If you want to keep the settings, make a backup of `%APPDATA%/Cryptomator` and restore it after re-installing 1.4.15.

**Comment by infeo** [comment]
Cryptomator 1.4.13 is not the most recent version of the 1.4.x branch and the actively maintained branch is 1.5.x, therefore i consider this not as an issue anymore.
