### ISSUE TITLE
Bundle VC++ Runtime Installer with Windows Installer

### ISSUE THREAD

**Issue by Riajyuu** [cryptomator/cryptomator-win#28]
![image](https://user-images.githubusercontent.com/16912240/78213090-1ccd6180-74a1-11ea-9948-575743e0d801.png)

### Motivation

Starting from 1.5.0, the 1.3.0 dokany vault requires VC++ 2019 x86 runtime (minimal version 14.21.27702). But that minimal runtime is not usually occurring in most Windows users' computer.

### Considered Alternatives

1. provide additional assets in release
2. provide a link in client

### Additional Context

I did resolved this very quickly myself, but my parents can't.

**Comment by overheadhunter** [comment]
We include and install vc_redist since commit d3eda6a:

https://github.com/cryptomator/cryptomator-win/blob/d3eda6ae8036d629b7783cfb3b98c1ad76558446/resources/innosetup/setup.iss#L72-L73

However, this is only the x64 version.

@Liryna Do we need only the x86 version or both?

**Comment by Liryna** [comment]
The x86 vc redist is needed by the msi because he also package the x86 library / sample files.
This should have been optional 😢 
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs#L229-L260

For information, we are looking to fully remove the dependency in the next release.
https://github.com/dokan-dev/dokany/issues/660

**Comment by Liryna** [comment]
The  new release include has a installer without the VC redist dependency
See the installer with noVC https://github.com/dokan-dev/dokany/releases/tag/v1.4.0.1000

**Comment by infeo** [comment]
With 73dbdbc1e7135cde4a83b401cae9589d74cbfefa we switched to noVC isntaller.
