### ISSUE TITLE
Cryptomator 1.5 on Windows 8.1

### ISSUE THREAD

**Issue by Pantos** [cryptomator/cryptomator-win#30]
I'm running Windows 8.1 and i'm surprised that Cryptomator 1.5 now is Win 10 only. Are there any plans to change this? I'm using Cryptomator daily, but this is a real showstopper...

**Comment by tobihagemann** [comment]
We are currently discussing this option: https://community.cryptomator.org/t/1-5-0-final-issue-with-windows-7-esu-and-8/5232

**Comment by overheadhunter** [comment]
At the time of writing this, 8.1 might still be an option according to [Oracle](https://www.oracle.com/java/technologies/javase/products-doc-jdk14certconfig.html) and I just noticed that even Windows 7 is supported via [AdoptOpenJDK](https://adoptopenjdk.net/supported_platforms.html#openjdk14_platforms).

I see two options here:
1. We could add a separate installer for legacy systems
2. We could add a warning in a single unified installer, if a user attempts to install Cryptomator on such a system (instead of blocking it).

**Comment by overheadhunter** [comment]
Closed in 4d4bb15
